#!/usr/bin/env python
import re
import sys
import urllib

session = "agVzaGVsbHISCxIHU2Vzc2lvbhjyvem56U0M"

def usage():
    print "Python REPL"
    print "Usage: >>> '1,2,3'.split(',')"
    sys.exit(0)

if len(sys.argv) == 1 or sys.argv[1] == '-h':
    usage()

args = urllib.urlencode({'statement': ' '.join(sys.argv[1:]),
                         'session': session})

result = urllib.urlopen("http://shell.appspot.com/shell.do?%s" % args).read()
if re.search("Status: 200 OK", result.split("\r\n")[0]):
    print "\n".join(result.split("\r\n")[6:])
else:
    print result
