#!/usr/bin/env python
import os
import re
import sys
from pipe import * # http://pypi.python.org/pypi/pipe/1.3
from subprocess import Popen, PIPE

if len(sys.argv) > 1 and sys.argv[1] == '-h':
     print "stats: Calcule des status sur quelqu'un"
     print "N'a besoin que d'une partie de son nom pour le retrouver (perl regex)"
     print "Exemple: stats oa"
     sys.exit(0)

search = re.search('[a-zA-Z0-9*.]*', sys.argv[1] if len(sys.argv) > 1 else '.*')
if search is None or search.group(0) == '':
    print "Stats de qui ?"
    sys.exit(0)
else :
    search = search.group(0)

def wc(logfile):
     return int(Popen(['wc', '-l', os.path.join('logs/users', logfile)],
                      stdout=PIPE).communicate()[0].split()[0])

stats = os.listdir('logs/users') \
    | where(lambda user: re.search(search, user, re.IGNORECASE) is not None) \
    | select(lambda user: (user, wc(user))) \
    | as_dict

if len(stats) > 0:
     stats.iteritems() \
         | sort(cmp=lambda x, y: y[1] - x[1]) \
         | select(lambda stat: "%s: %d" % (stat[0], stat[1])) \
         | concat \
         | lineout

if len(stats) > 1:
     print 'Total: %d' % sum(stats.values())
