#!/usr/bin/env python
import re
import sys
import DNS


if len(sys.argv) == 1 or sys.argv[1] == "-h":
    print 'Get last status of someone on twitter'
    print "Usage: %s sizeof" % sys.argv[0]
    sys.exit(0)

try:
    username = re.search('[a-zA-Z0-9*.]*', sys.argv[1]).group(0)
    DNS.DiscoverNameServers();
    r = DNS.Request('%s.twitter.any.io' % username, qtype='txt');
    ans = r.req()
    print ans.answers[0]['data'][0]
except Exception as ex:
    print "Humph, I can't find this twitter user ..."
