#!/usr/bin/env python

from urllib import urlopen, urlencode
import sys
import re

def _tiny(match):
    url = match.group()
    if len(url) >= 30:
        return urlopen("http://tinyurl.com/api-create.php",
                              data=urlencode(dict(url=url))).read().strip()
    else:
        return url

def tiny(string):
    return re.sub('http://[^ ]+', _tiny, string)


if len(sys.argv) == 2 and sys.argv[1] == '-h':
    print "tinyurl: Shorten urls, you can give a whole text, it will find urls"
    print "and shorten only longest ones"
else:
    print tiny(' '.join(sys.argv[1:]))
