#!/usr/bin/env python

from urllib import urlopen, urlencode
import sys
import re

def _tiny(match):
    url = match.group()
    if len(url) >= 30:
        return urlopen("http://tinyurl.com/api-create.php",
                              data=urlencode(dict(url=url))).read().strip()
    else:
        return url

def tiny(string):
    return re.sub('http://[^ ]+', _tiny, string)

print tiny(' '.join(sys.argv[1:]))
