#!/bin/sh

if [ "$1" = "-h" ]
then
    echo "Find last sayed thing matching."
    echo "Usage : !dash"
    exit 0
fi
search="$*"
if [ -n "$search" ]
then
    grep -i "$search" logs/all_raw_messages | grep -v ' :!' | tail -n 1
fi
