#!/bin/sh
command="$(echo "$1" | sed 's#/#__SLASH__#g')"

usage()
{
    echo 'Usage: help COMMAND'
    echo '    With COMMANDS in :'
    echo $(ls -1 commands-enabled | grep -v :\\\|log | grep -v '~' | grep -v '#' | sed 's#__SLASH__#/#g')
}

[ "$command" = "-h" -o -z "$command" ] && usage || commands-enabled/$command -h
