#!/bin/sh
command="$(echo "$1" | sed 's#/#__SLASH__#g')"

usage()
{
    echo 'Usage: help COMMAND'
    echo '    With COMMANDS in :'
    echo $(ls -1 commands-enabled | grep -v :\\\|log | grep -v '~' | grep -v '#' | sed 's#__SLASH__#/#g')
}

if [ "$command" = "-h" -o -z "$command" ]
then
    usage
else
    if [ -x "commands-enabled/$command" ]
    then
        commands-enabled/$command -h
    else
        if [ -f "db/aliases/$command" ]
        then
            echo "$command is an alias to :"
            cat db/aliases/$command
        else
            echo "Don't know $command"
        fi
    fi
fi
