#!/bin/sh -f
mkdir -p db/note
key=$(echo "$1" | sed 's/\//_/g')
if [ -z "$key" -o "$key" = -f ]
then
        echo "Take notes, like :"
        echo "you: note key value"
        echo "you: note key"
        echo "the_biatch: value"
        exit
fi

if [ -z "$2" ]
then
        cat "db/note/$key"
else
        echo "$2" > "db/note/$key"
fi