#!/bin/sh -f
if [ "$1" = '-h' ]
then
   echo "$(basename "$0"): Run a command"
   echo "Usage: run NAME"
   echo "Example: (julien) alias pi >>> import math; print math.pi"
   echo "         (julien) run pi"
   echo "         (the-biatch) 3.1415926535897931"
   exit 0
fi

mkdir -p db/aliases

alias=$(printf "%s" "$1" | sed 's#/#__SLASH__#g')
args=$(printf "%s" "$*" | sed 's/^ *[^ ]* *//g' )

if [ -f "db/aliases/$alias" ]
then
    line=$(cat "db/aliases/$alias" | sed "s/|ARGS|/$(echo "$args" | sed 's/\\/\\\\/g;s/&/\\&/g;s#/#\\/#g')/g")
    command=$(printf "%s" "${line%% *}" | sed 's#/#__SLASH__#g')
    if [ -x "commands-enabled/$command" ]
    then
        args=$(echo "$line" | sed 's/^ *[^ ]* *//g' )
        printf '%s\n' "Alias running command '$command' with '$args'" >&2
        commands-enabled/$command $args
    fi
fi




