#!/bin/sh
usage()
{
    echo "Usage: translate from-to blah blah"
    echo "Example: translate en-fr shit"
}

[ "$1" = -h -o -z "$1" ] && usage && exit

from=fr
to=en
if echo "$1" | grep -q -- '-'
then
    from="$(echo $1 | cut -d- -f1)"
    to="$(echo $1 | cut -d- -f2)"
    shift
fi
wget -qO- "http://ajax.googleapis.com/ajax/services/language/translate?v=1.0&q=$*&langpair=$from|$to" | sed 's/.*"translatedText":"\([^"]*\)".*}/\1\n/';
