#!/usr/bin/env python

from httplib2 import Http
import sys
import re

if len(sys.argv) == 1 or '-h' in sys.argv[1]:
    print "Expand a tinyurl"
    sys.exit(0)


def _untiny(match):
    url = match.group()
    request = Http().request(url, 'HEAD')
    return request[0].previous['location']

def untiny(string):
    return re.sub('http://[^ ]+', _untiny, string)

print untiny(' '.join(sys.argv[1:]))
