#!/bin/sh
usage()
{
    echo 'Query something on en.Wikipedia.org ...'
    echo "Usage: $(basename "$0") sex"
    exit
}

[ "$1" = -h -o -z "$1" ] && usage
result="$(dig +short txt $(echo $* | sed -e 's/ /_/g' | grep -o '[a-zA-Z0-9_()]*' | head -n1).wp.dg.cx | tr -d \\ | grep -v '^;;')"
[ -n "$result" ] && echo "$result" || echo "Humph, I can't find anything about this ..."
