#!/bin/sh -f
#
# This is a basic example hook for incoming messges (pubmsg, privmsg)
#
# Its role is simple, this hook will try to run executables in the
# 'commands-enabled' folder. But if the executable is not found, it
# will try to run the catchall binary 'run'
#
# Example:
#   If someone says: 'eval 1 + 1'
#   Then if commands-enabled/eval exists this hook will try to execute :
#       commands-enabled/eval 1 + 1
#   else if commands-enabled/run exists, this hook will try to execute :
#       commands-enabled/run eval 1 + 1
#
# Exemple : hooks-enabled/pubmsg 'mandark' '~mandark@mandark.fr' '#zomgffs' '' 'say Hello world !'

mkdir -p "logs/users"
now=$(date "+%Y-%m-%d %H:%M:%S")
s_user="$(printf %s "$1" | sed 's#/#__SLASH__#g')"
s_host="$2"
t_user="$3" # The channel, for "pubmsg" hook
t_host="$4"
shift 4
sentence="$*"
command="$(echo "${1%% *}" | sed 's#/#__SLASH__#g')"
args="$(echo "$1" | sed 's/[^ ]*//')"

if [ -x "advanced-commands-enabled/$command" ] && [ -f "advanced-commands-enabled/$command" ]
then
    printf '%s\n' "Running advanced command '$command' with '$args'" >&2
    echo "RAW $(commands-enabled/$command $args)"
elif [ -x "commands-enabled/$command" ] && [ -f "commands-enabled/$command" ]
then
    printf '%s\n' "Running command '$command' with '$args'" >&2
    echo "MSG $t_user $(commands-enabled/$command $args)"
elif [ -x "commands-enabled/run" ]
then
    printf '%s\n' "Running command run with '$command $args'" >&2
    echo "MSG $t_user $(commands-enabled/run $command $args)"
fi

printf "%s\n" "$now $s_host $t_user $t_host $sentence" >> "logs/users/$s_user"

