#!/bin/sh -f
#
# This is a basic example hook for incoming public messges
#
# It role is simple, this hook will try to run binaries in the 'commands' folder
# But if the binary is not found, it will try to run the catchall binary 'run'
#
# Example:
#   If someone says: 'eval 1 + 1'
#   Then if commands/eval exists this hook will try to execute :
#       commands/eval 1 + 1
#   else if commands/run exists, this hook will try to execute :
#       commands/run eval 1 + 1

mkdir -p "logs/users"
now=$(date "+%Y-%m-%d %H:%M:%S")

s_user="$(printf %s "$1" | sed 's#/#__SLASH__#g')"
s_host="$2"
t_user="$3"
t_host="$4"
shift 4
arguments="$*"

command=$(printf "%s" "${1%% *}" | sed 's#/#__SLASH__#g')
first_letter=$(expr substr "$1" 1 1)
args=$(printf "%s" "$1" | sed 's/^ *[^ ]* *//g' )

if [ -x "commands/$command" ] && [ -f "commands/$command" ]
then
    printf '%s\n' "Running command '$command' with '$args'" >&2
    commands/$command $args
elif [ "$first_letter" != '/' ] && [ -n "$first_letter" ] && [ -x "commands/$first_letter" ]
then
    commands/"$first_letter" $(expr substr "$1" 2 ${#1}) $args
elif [ -x "commands/run" ]
then
    commands/run $command $args
fi

printf "%s\n" "$now $s_host $t_user $t_host $arguments" >> "logs/users/$s_user"

